services:
  #-- Banco de Dados da Aplicação --#
  postgres_db:
    image: postgres:16
    container_name: ms-platform-auth-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #-- Banco de Dados do Keycloak --#
  postgres-keycloak-db:
    image: postgres:16
    container_name: database-keycloak
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_USER_DB}
      POSTGRES_PASSWORD: ${KEYCLOAK_PASSWORD_DB}
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - keycloak-net

  #-- Serviço do Keycloak --#
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak-db
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_USER_DB}
      KC_DB_PASSWORD: ${KEYCLOAK_PASSWORD_DB}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8083:8080"
    command: start-dev
    depends_on:
      - postgres-keycloak-db
    networks:
      - keycloak-net

volumes:
  postgres_data:
    driver: local
  keycloak_db_data:
    driver: local

networks:
  keycloak-net:
    driver: bridge