spring:
  config:
    activate:
      on-profile: with-keycloak
  
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:platform-auth}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/platform}
            authorization-uri: ${KEYCLOAK_AUTH_URI:http://localhost:8080/realms/platform/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8080/realms/platform/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:http://localhost:8080/realms/platform/protocol/openid-connect/userinfo}
            user-name-attribute: preferred_username

keycloak:
  realm: ${KEYCLOAK_REALM:platform}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  resource: ${KEYCLOAK_CLIENT_ID:platform-auth}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:secret}
  ssl-required: external
  public-client: false
  confidential-port: 0
