spring:
  application:
    name: ms-platform-auth

  docker:
    compose:
      file: docker-compose.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:authdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true