spring:
  application:
    name: ms-platform-auth
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?currentSchema=${CURRENT_SCHEMA}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    br.com.soejin.auth: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

keycloak-admin:
  server-url: ${KEYCLOAK_URL:http://localhost:8083}
  realm: ${KEYCLOAK_ADMIN_REALM:master}
  client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  username: ${KEYCLOAK_ADMIN:admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:Adm1n_P@ssw0rd_2025!} # Reutilizando a senha!
